// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVBzUp2VmsPASVgAnb6n6BkSfJYNUQ5Y',
    appId: '1:505968651145:web:4f577ec49c6c03b1ba8f58',
    messagingSenderId: '505968651145',
    projectId: 'imm-app-project',
    authDomain: 'imm-app-project.firebaseapp.com',
    storageBucket: 'imm-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0mIXIADtwyzS48_RrJ5bkWl5wG7BGHQ',
    appId: '1:505968651145:android:441c612ee6b41663ba8f58',
    messagingSenderId: '505968651145',
    projectId: 'imm-app-project',
    storageBucket: 'imm-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAty-Ye2vwIevXPelLPairAlI-aoPgv6Qg',
    appId: '1:505968651145:ios:27e0475ea3754883ba8f58',
    messagingSenderId: '505968651145',
    projectId: 'imm-app-project',
    storageBucket: 'imm-app-project.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.immApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAty-Ye2vwIevXPelLPairAlI-aoPgv6Qg',
    appId: '1:505968651145:ios:27e0475ea3754883ba8f58',
    messagingSenderId: '505968651145',
    projectId: 'imm-app-project',
    storageBucket: 'imm-app-project.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.immApp',
  );
}
